chmod 400 streamlit.pem
ssh -i "streamlit.pem" ubuntu@<Your Public DNS(IPv4) Address>

sudo apt install python3

sudo apt-get update
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
echo "PATH=$PATH:$HOME/miniconda/bin" >> ~/.bashrc
source ~/.bashrc

conda env create -f environment.yml
